title: The Fast Track to Julia
#baseurl: "C:/Users/steff/Documents/GitHub/Julia-Cheat-Sheet"
baseurl: "/Julia-Cheat-Sheet"
description: "The Fast Track to Julia - Julia Cheat Sheet"
github_username: JuliaDocs
markdown: kramdown


highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: julia


t:
  en:
    name: "English"
    fast-track: "The Fast Track to"
    quick-dirty: "A quick and dirty overview of"
    github-1: "This page's source is"
    github-2: "located here"
    github-3: "Pull requests are welcome!"
    translate: "Help translate!" # Not used for `en`